### ISSUE TITLE
用shadowsocks，连接不了。

### ISSUE THREAD

**Issue by ruleroller** [AnyFlowApp/AnyFlowApp-issues#10]
work mode选的global proxy，规则没有写，最后规则外选的是proxy。其它设置皆默认，ss用的是82端口，IP和密码确认都没填错。VPN图标也出来了，可就是连不上。

规则是要用户自己写的吗？

现在处于没用上的状态。怎么感觉比surge都难，求救！！

**Comment by ruleroller** [comment]
加密选的是aes-256-cfb

**Comment by ruleroller** [comment]
手机是iPhone 5s ，系统是 9.3.5

**Comment by alexazhou** [comment]
配置没问题，可能的原因

1，目前版本修改配置后需要重新连接 VPN 才生效
解决方法：重新连接

2，DNS 配置不正确
解决方法：config -> Advanced -> Addition  DNS 中输入，"8.8.8.8, 114.114.114.114, 233.5.5.5"

3，服务器被认证了
确认方法：ping 服务器地址确保可以连接成功

**Comment by ruleroller** [comment]
刚才关闭状态下，尝试着打开ignore System DNS，再重新连接，终于连上了。

之后先断开，又将此选项关闭，重新连，也能连上了。

不过，总还是感觉怪怪的。


规则书写只能一个个录入么，能否提供文本方式的供直接编辑？和surge的规则通用吗？

**Comment by alexazhou** [comment]
目前只能手动每条输入，后续会支持从 URL 导入，兼容 Surge 规则
