### ISSUE TITLE
建议和一些反馈

### ISSUE THREAD

**Issue by bdbai** [AnyFlowApp/AnyFlowApp-issues#14]
- 希望在 Saved Sessions 列表中增加重命名会话、分类等功能。
- Request Detail 页面的信息没法复制，也不能导出请求。
- 查看响应实体较大的请求时，误触下方 Viewer 导致应用卡顿，影响体验。建议另外加个提醒。

望改进，期待下一次更新。

**Comment by alexazhou** [comment]
多谢反馈

1，很靠谱的建议
2，的却不方便，我会加上导出的功能
3，我研究下看能否提升性能，或者减少误触发的可能
