### ISSUE TITLE
关于 GEOIP

### ISSUE THREAD

**Issue by aieu** [AnyFlowApp/AnyFlowApp-issues#16]
Volue: CN
Policy: Direct

然后浏览器打开 ip.cn ，发现走的是代理...

**Comment by alexazhou** [comment]
确认有这个现象，原因是目前 GeoIP 查询库有些问题，被我暂时屏蔽掉了

我正在调整这一块的代码，下个版本 v1.3 GeoIP 规则会恢复正常

**Comment by alexazhou** [comment]
已经调整好了，等待发 1.3 版本

**Comment by shyrz** [comment]
GEOIP 问题1.3 版本已经解决 : )

**Comment by aieu** [comment]
Thanks!
