### ISSUE TITLE
suffix 规则

### ISSUE THREAD

**Issue by aieu** [AnyFlowApp/AnyFlowApp-issues#17]
Value    .cn
Policy   Direct

规则无效....最终还是走默认的proxy

**Comment by alexazhou** [comment]
suffix 规则并不是完全的字符串匹配，我举例说明一下：

例如添加了一条 suffix 规则：

```
value = abc.com
```

那么 

* x.abc.com 符合
* xyz.abc.com 符合
* abc.com 符合
* xabc.com 不符合

也就是说如果要匹配上，要么域名完全相等，要么域名字符串以

 **"." + value**

 结尾 

就这个例子说，如果要匹配 **.cn**，那么设置 value ＝ cn 的 suffix 规则就可以了

**Comment by alexazhou** [comment]
另外调试规则的时候，可以用 rule test 界面来测试，会比较方便 +_+

**Comment by aieu** [comment]
Thanks，正在挖掘功能...^_^

**Comment by learnsss** [comment]
@alexazhou 这个 rule test 和surge界面的不太一样，感觉不会用，另外ipad版的排版还是有问题吧，还是对不齐，还有一点是昨晚更新到现在掉线过一次。

**Comment by alexazhou** [comment]
1，rule test 界面使用方法很简单，就是输入你要访问的地址，无论是域名或者 ip 都可以，然后 AnyFlow 会给出匹配的结果

2，ipad 是哪里排版有问题呢，我自己没发现来着

3，嗯，好像偶尔会掉线，原因未知=_=，把规则导入搞定后，会集中查一下

**Comment by alexazhou** [comment]
我发现目前 rule test 界面仅在 work mode 设置为 rule proxy 模式下，工作是正常的。。。
