### ISSUE TITLE
ss是自己实现的吗？能否支持OTA

### ISSUE THREAD

**Issue by aieu** [AnyFlowApp/AnyFlowApp-issues#2]
这个应该是硬需求，特别是对自建ss的人来说，开启OTA几乎是常识。
这么一来，AnyFlowApp会支持ss的OTA吗？

**Comment by alexazhou** [comment]
SS 是内部实现的，OTA 会加上。

因为追求效率的原因， AnyFlow 是在内部实现了自己的一个全异步的SS， 优点不用说，但目前这个内部的 SS 功能还不够完善 T_T，例如目前只支持 AES 系列的加密方式以及没有 OTA，这些都会逐渐加上。

ps：实际上外挂其他的开源组件例如 shadowsockslibev 来转换，就可以直接支持所有的加密方式，但会多一次转发影响效率，并且占用内存也更多

**Comment by alexazhou** [comment]
今天上线的 v1.2 版本已经支持 OTA
