### ISSUE TITLE
iPad还是有重叠

### ISSUE THREAD

**Issue by imaqine** [AnyFlowApp/AnyFlowApp-issues#21]

**Comment by alexazhou** [comment]
横屏模式下吗，可以给个图么？

我这边没发现 +_+

**Comment by imaqine** [comment]
http://i.imgur.com/j8SaSoH.jpg

**Comment by alexazhou** [comment]
收到，请问 ipad 软件版本是多少？

我想办法测试一下

**Comment by imaqine** [comment]
iOS9.3.5

**Comment by alexazhou** [comment]
多谢反馈

**Comment by imaqine** [comment]
嗯

**Comment by learnsss** [comment]
@alexazhou 对的，我的也有这个情况就是不知道怎么发图,,ԾㅂԾ,,，系统也是9.3.5，而且不能横屏。

**Comment by CoderRunner** [comment]
iPad mini2
iOS 9.3.5
http://ww1.sinaimg.cn/large/659d45f8gw1fauu6yotltj216o1kw788.jpg

**Comment by alexazhou** [comment]
@CoderRunner 

收到，这是横屏模式下的一个 bug，下一版会修复 :-P

**Comment by CoderRunner** [comment]
http://ww1.sinaimg.cn/large/659d45f8gw1fauu9l729xj216o1kwqmf.jpg

**Comment by alexazhou** [comment]
首页的旋转错位在 v1.3 已经修正了，输入框那里已经修复，等待发 v1.4 版本

**Comment by alexazhou** [comment]
iPad 错位已经在 v1.4 修复
