### ISSUE TITLE
闪退及一些小问题

### ISSUE THREAD

**Issue by learnsss** [AnyFlowApp/AnyFlowApp-issues#22]
1、2天内出现4次闪退，3次是从浏览器切到anyflow出现的，1次是观看视频中不知何故出现的；
2、http requests里抓包出来里面网址及内容不可复制，手动输入太麻烦了(ˉ▽ˉ；)...，望加入可复制功能；
3、日志的保存是否可以加入定期删除（比如1-2天），这几天日志没删占了9个G的内存(；′⌒`)。

**Comment by alexazhou** [comment]
多谢反馈

1，这里的闪退说的是 AnyFlow 前台 APP 闪退，还是后台 VPN 模块退出呢？
2，会加入复制功能
3，这里说的日志是 session 而不是 log 对吧，会加入两个功能
* 自动删除超过一定时间的 session
* 如果打开 Analyze ，也就是记录所有流量，那么在连接 VPN 时会给出提示
如果没有这方面的需要，可以不用打开 analyze 的选项，消耗资源会更少一些

**Comment by learnsss** [comment]
@alexazhou 
1、浏览器是前台，抓取页面广告时切回来就闪退了；视频是后台（就出现过1次，不知何因）
3、恩，就是那个saved sessions

**Comment by alexazhou** [comment]
1，前台 app 闪退很可能的原因是要显示的记录，还没有完全结束，所以信息不全，我会在 v1.3 之后梳理一下这方面的代码

3，了解啦，功能会加上，就是需要些时间:-P

**Comment by alexazhou** [comment]
稳定性问题在 1.4.1 中基本已经解决
