### ISSUE TITLE
Analytic下的Http requests出现空网址，点击前台闪退

### ISSUE THREAD

**Issue by luckyWK** [AnyFlowApp/AnyFlowApp-issues#23]
有ID，有时间，类型unknown，点击之后APP闪退

**Comment by alexazhou** [comment]
确认有这个问题，不过几率比较小，一直没能稳定复线，所以原因未知 (///▽///)

把批量导入规则弄完之后，我来查一下这个吧

**Comment by CsHeng** [comment]
TF 1.3 版本。。。（好像软件里面没有地方可以看到软件具体的版本号和build？）

我发现TG的请求好像都是挂了的。。这种情况列表外面是显示：Unknown，所以我没开新的issue，直接扔这了

无论用Rule Proxy还是全局，都无法正常请求成功，Download为0.

![image](https://cloud.githubusercontent.com/assets/1481956/21384105/ec17b368-c7a3-11e6-9c8b-cf43a345ea47.png)

**Comment by alexazhou** [comment]
多谢反馈，已经复现了 TG 不能用， 晚点我来查下是为啥

Analytic下 出现显示空记录的问题，在下个版本 ( v1.4 ) 修正

软件里目前确实没有看版本号和 build 的地方，也在下个版本加上

**Comment by alexazhou** [comment]
至 1.4.1 版本，已经修复
