### ISSUE TITLE
TF大概申请之后大概多久会发

### ISSUE THREAD

**Issue by CoderRunner** [AnyFlowApp/AnyFlowApp-issues#24]

**Comment by CoderRunner** [comment]
TF大申请之后大概多久会发..

**Comment by alexazhou** [comment]
1，TF 的测试人员是每天晚上都统一添加
2，不出意外的话，后天也就是 19 号晚上，会提交一个版本进行 TF 测试

**Comment by CoderRunner** [comment]
昨天申了没反应啊，大概是kaiser.xxx@gmail的邮箱

**Comment by alexazhou** [comment]
我查了确实已经把你加到 External Testing 名单里面去了，xxx 一共八个字母
是不是需要我发布 TF 版本之后你才会收到邮件？

**Comment by CoderRunner** [comment]
不清楚啊…

**Comment by alexazhou** [comment]
应该是这样，这样吧，等我先提交测试版本

如果到时你还没有收到测试邀请，再联系我就好。
