### ISSUE TITLE
Telegram 收发信息一直处于 updating 状态

### ISSUE THREAD

**Issue by shyrz** [AnyFlowApp/AnyFlowApp-issues#29]
*AnyFlow v1.3*

更新v1.3版本后，所有 Proxy 模式下，Telegram 收发信息顶部标题栏处于无限 updating 状态，Rule Test 以及 HTTP Ruquest 显示流量确实走了代理，但是 updating 状态仍然存在，同时收发信息延迟相当高

**Comment by shyrz** [comment]
其他 App 如 TweetBot， Instagram 等都很流畅

**Comment by alexazhou** [comment]
确实是有这个现象，可能是 Telegram 是通过 TCP 协议来通讯的，而目前  Proxy Rule 还没有作用在 TCP 协议上面，我会去抓日志确认一下这个情况。

**Comment by alexazhou** [comment]
已经确定问题了，AnyFlow Core Proxy 在解析 Telegram 的 HTTP 流的时候，有个地方判定出错了。。。

1.4 版本中修正

**Comment by shyrz** [comment]
谢谢 :+1:

**Comment by alexazhou** [comment]
v1.4 版本已经提交 TF 了，这部分修改还需要测试，没来得及合并过来，再下个版本应该 ok

ps：目前大约是每周一个版本

**Comment by CoderRunner** [comment]
tg不能上就没有办法一直开着😂，用tg的时候得切到小火箭。现在就是AnyFlow和小火箭各种切换..

**Comment by alexazhou** [comment]
1.4.1 已经修复
