### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by learnsss** [AnyFlowApp/AnyFlowApp-issues#30]
1、ipad点击add rule group立即闪退（多次尝试，卸载重装还是闪退），而且还是有重叠问题；
2、iphone中rule test完点击rule出现闪退。

——————————————————————————————————————
3、global里advanced各项是做什么用，这个能解释下吗？

**Comment by shyrz** [comment]
1. 应该是 UI 布局问题，耐心一点等待修复吧

2. iPhone 6S Plus iOS10.2(14C92) 多次测试没有出现这个问题（如果可以的话希望你也能留下设备版本以及系统版本，开发者可能会用得到

3. Advanced 中有四项功能：
    1. **WIFI ACCESS**：建立一个 HTTP 代理服务器，通过连接同一个 WiFi 可以使用 AnyFlow 的代理，默认端口2008
    2. **DNS**：AnyFlow 可以修改你的默认DNS， 开启 Ignore 选项会忽略系统 DNS，Addition DNS 可以填写你自己设置的 DNS 服务器，用英文逗号隔开
    3. **SKIP PROXY**：跳过代理，添加在下面的域名或者 IP 将会跳过 AnyFlow 代理服务器，你可以通过这个功能修复一些 App 的兼容性问题
    4. **BYPASS TUN**：Bypass System 选项开启旁路系统，AnyFlow 的 TUN 只支持 TCP 协议，添加在下面的 IP 域将会允许其他协议通过，同时这些 IP 域也会跳过 AnyFlow 代理服务器

**Comment by alexazhou** [comment]
@Mr-WK 
1，闪退的 iPad 的型号和系统版本是？以及是否越狱？我好尝试去复现。重叠问题已知，目前还没来得及修。
2，找到原因了，应该是目前 Rule Test 界面在 VPN 连接状态下，对域名进行 Test 有 bug，DNS 请求回不来所以出错，下个版本修复
3，呃，里面每项下面都有说明（英文），其实选项不难懂，主要是这个涉及到一些网络方面的知识，我回头给 APP 写个完整的说明吧

@Phantr4x 

Thanks

**Comment by learnsss** [comment]
@alexazhou 型号：ipad mini 系统：9.3.5  未越狱

**Comment by learnsss** [comment]
@Phantr4x  好的，谢谢了。

**Comment by alexazhou** [comment]
iPad mini Add Rule Group 闪退已经确认，下个版本修复。这个 bug 应该是会在 ~~iOS 9 系统~~ iPad下出现。

**Comment by alexazhou** [comment]
已经修正，等待 v1.4 发版
