### ISSUE TITLE
需要一个详细的使用说明

### ISSUE THREAD

**Issue by learnsss** [AnyFlowApp/AnyFlowApp-issues#31]
我的配置：work mode:rule proxy；advanced:DNS和bypass system（这个是干什么用的(◎﹏◎)）勾选了；ss账号仔细核查输入没问题；规则导入别人的和自己加了点；default policy:direct。 这样配置下来浏览网页没问题，但是听音乐（需好几秒钟才能播放），聊QQ和微信（一直显示无法连接服务器）发消息还是能发得等个几十秒钟才能发出去。 这究竟是什么问题，是不是我长得太帅了！！！o(^▽^)o  
———————————————————————————————————————————————
感觉真的需要写一个详细介绍使用，对于很多比较懂得大神来说很简单啦，对于我们一些小白来说实在是脑袋大，因为和之前用过的很多软件感觉都不太一样，感觉就是上手太难（其实是我太菜,,ԾㅂԾ,,）。

**Comment by alexazhou** [comment]
标题我帮你修改了，请不要使用这样的标题，会给很多人以误导。

对照众多同类软件来说，AnyFlow 是少有的完全自己实现全套组件的，包括 Proxy ， SS 等，可以说是诚意十足。这些都是为了提升速度和效率，不可能会奇慢无比(/ω＼) （当然是在正确使用的情况下）   

从你的描述来说，有可能是规则的问题，是不是添加了某些规则导致大部分请求走了 proxy？可以对照 Request 看一下。

如果不清楚怎么编辑规则的话，我推荐导入 ABCLite 提供的规则，包含了常用的访问外国网站，以及国内广告拦截，日常使用足够了

http://www.abclite.cn/Abclite_ADB.conf

用这一个规则就够了，不用再添加其他的。

这几天我会提供一个 Trouble-shooting 文档，可以对照解决问题

**Comment by learnsss** [comment]
@alexazhou 对不起，以后起标题会注意的。
1、我看了下之前导入的规则基本都是reject，导入ABCLite后恢复正常，编辑规则自己也只会编辑reject，其它基本不会，还是希望有个比较完整的说明（对于像我一样少数的小白可能会有一些帮助）。
2、之前那个ipad点击add rule group闪退确认了吗？这个我下午就试了好多次一点就闪退，这个望修复！
3、能加入TF吗，昨天申请了一直没有回信！

**Comment by alexazhou** [comment]
1，会提供一个详细的说明，请稍等两天
2，我刚去找到设备，确实有这个问题（应该是 ~~iOS9 系统~~ iPad下出现）
3，别着急，TF 是有测试版本的时候才会收到邮件，我下次发测试版本的时候，把你加入进去就好了。为了确保没漏掉，你可以到 Twitter 私信给我邮箱

**Comment by learnsss** [comment]
@alexazhou 恩，好的，刚去关注了推特。

**Comment by learnsss** [comment]
@alexazhou 我在软件里手动关闭接着开启后，又不正常工作了，表现为：网页打不开，软件也连不上网，只有关机重启后才恢复正常，然后我又从软件里关闭在开启，又出现了上述情况。这个情况就我一个人出现吗？想问问有什么解决办法！

**Comment by alexazhou** [comment]
删掉所有的 Reject 规则试试看吧，有些 APP 在被 Reject 时可能会引起很高频率的重试，导致不正常。

如果没有解决，那么我给你写个 Troub-Shooting 文档，一项一项对着查询吧

**Comment by learnsss** [comment]
@alexazhou    reject全部删掉后仍然无法连接，不知道我哪儿的问题。/(ㄒoㄒ)/~~

**Comment by alexazhou** [comment]
@Mr-WK 

我把目前已知的情况，整理成一个故障排查文档了，你对照这个排查一下吧。如果还有问题，那就按照里面说的内容，发 bug 报告给我，我好查原因

https://github.com/AnyFlowApp/AnyFlowApp-issues/blob/master/Trouble-Shooting.md
