### ISSUE TITLE
开启代理后，代理无法正常使用，手机发热

### ISSUE THREAD

**Issue by CoderRunner** [AnyFlowApp/AnyFlowApp-issues#32]
config->advanced修改完成后，reload tunnel会一直转圈，无法结束

同理，修改完规则之后会停留在apply rules一直转圈

**Comment by alexazhou** [comment]
有没有配置规则？

如果有的话，试试把所有规则组 disable 掉之后（取消勾选就是 disable ），看还会有没有出现发热

如果是跟规则有关系，那么特别注意添加的 Reject 规则，Reject 速度很快，而有些请求 Reject 掉之后，宿主 APP 会有很高频率的重试导致发热

**Comment by alexazhou** [comment]
另外是否开启了 Analytics ？

这个选项会记录所有的流量到文件系统，会一定程度上增加功耗

还有日志级别是不是设置为 warn 以上？

warn 是默认的日志级别，太低的日志级别会产生很多日志，也可能会导致发热

**Comment by CoderRunner** [comment]
配置了Abclite的规则
开启了Analytics

把换了另一个规则组没有问题了，谢谢

另外我一直不是很理解reject和drop的区别，可否给出一个具体的例子解释下？
我将全部reject替换成drop会有区别吗？

**Comment by alexazhou** [comment]
可以将全部的 Reject 换成 Drop

因为 Drop 这个策略是 AnyFlow 新引入的，我举例说明一下，我装了个视频 APP，会访问 abc.com 获取广告，如果对 abc.com 配置了 Reject 规则，那么这个视频 APP 访问 abc.com 的请求会在发送完 HTTP 请求头之后，也就是 AnyFlow 从 HTTP 头中读取到他要连接的地址时，就立刻断开 TCP 连接。

这时取决于这个视频 APP 的策略，可能就不再请求了，也可能死循环一般在很短的时间里面重试几百次。

如果配置了 Drop 规则，那么 AnyFlow 读取完 HTTP 头之后，就会丢弃请求，不向外转发，但是保留 TCP 连接。视频 APP 那边就只能等待请求超时了，至少需要好几秒才可能有下一次重试。

**Comment by CoderRunner** [comment]
明白了，多谢

**Comment by CoderRunner** [comment]
我发现不是配置和Analytics的问题
我连家里的wifi才会这样，用4G和别的wifi就没有问题，不知道为什么..

**Comment by CoderRunner** [comment]
Drop类型的，这样的规则无法导入？

DOMAIN-SUFFIX,ad.sina.com.cn,Drop
DOMAIN-SUFFIX,adm.leju.sina.com.cn,Drop
DOMAIN-SUFFIX,atm.sina.com,Drop
DOMAIN-SUFFIX,beacon.sina.com.cn,Drop
DOMAIN-SUFFIX,dcads.sina.com.cn,Drop
DOMAIN-SUFFIX,sax.sina.cn,Drop
DOMAIN-SUFFIX,sax.sina.com.cn,Drop
DOMAIN-SUFFIX,tjs.sjs.sinajs.cn,Drop

**Comment by alexazhou** [comment]
@CoderRunner 

这是哪个软件的规则，还是你自己编辑的呢 ？

目前我不知道有其他 app 里面会出现 Drop 规则，所以只处理了 Direct，Proxy，Reject 。

**Comment by CoderRunner** [comment]
@alexazhou 对，是我自己编辑的。。
我觉得处理的时候可以把Drop加上，毕竟这是AnyFlow独有的

**Comment by alexazhou** [comment]
对你描述的在你家 wifi 下无法 Proxy 的问题，我后续会加入一个诊断功能，用来检测在特定环境下的连接情况，找到问题的所在。

**Comment by alexazhou** [comment]
从文件导入 Drop 规则我给加上，v1.4 就有了

**Comment by CoderRunner** [comment]
之前用v1.3 TF版的时候家里的 wifi 没问题，昨天从 app store 下载了v1.3 之后就有问题了
具体我还得再观察下，如果明确了原因再来提 issue

**Comment by alexazhou** [comment]
好，另外可以看看是否 DNS 的原因，设置 Addition DNS 可以解决这个问题，当然如果默认设置没改过，就不用动了

另外我这两天也会提供一个 Troub-Shooting 文档。

**Comment by CoderRunner** [comment]
说到Addition DNS设置问题
我想要添加DNS的时候，发现是数字键盘，不能输入英文逗号

**Comment by alexazhou** [comment]
😳，惊 呆 了 我。

先从别的地方粘贴过来吧，下个版本修正。

**Comment by CoderRunner** [comment]
做了个简单的测试，给你发了邮箱
邮箱用的这个，如果没发错的话。。
 YWxleGF6aG91QDE2My5jb20=
