### ISSUE TITLE
一处bug反馈及若干细节建议及。。。希望zici的功能。。。溜

### ISSUE THREAD

**Issue by unknowntokyo** [AnyFlowApp/AnyFlowApp-issues#33]
**# bug反馈：**
---advanced里面的skip proxy我在里面输入多个文本，他好像只识别了一部分，

---在wifi下已经连接anyflow的情况下，手动通过通知中心关闭wifi（没测试远距离断开wifi和设置里面断开wifi），状态栏wifi标识会卡在变灰，而没出现4G，在4g已连接安逸flow的情况下连接wifi，状态栏正常显示。

**细节部分:**
---analytics界面的enable选项在没关掉vpn的时候disable之后，current session下的数据会清空。

---从request detail左滑至上一级有点掉帧。

---http request 最好能标记下哪个app使用的，当然能单独加个开关按照app名称分组显示最好啦2333，因为作为调试工具更实用方便一点。

---rule里面的搜索不能查询关键字，比如DOMAIN,api.smoot.apple.cn,Proxy，我输入apple或者smoot不能匹配到，

---还有1.3版本的有没有根据ip域名决定走代理还是直连，我看规则外的设置只能选一个，能不能根据ip的地址判定呢

---ui上的一些提示可不可以换一套风格，小火箭都不准备用这种提示了。

----节点需要加排序和显示延迟，节点密码出应该加一个隐藏的眼睛

----应用节点和rule的提示其实可以放后台操作一下

**希望支持的功能：**
*能根据规则对流量进行分流。

*希望支持SSR及最新加密方式，

*url-rewrite功能，

*---能否加入类似surge的autogroup功能，自动选择最优节点并可以自定义参数，这样节点质量不高或者因为墙的原因导致无法连接的用户可以多一个选择。

*希望可以对规则统计然后进行清理，因为好多人根本用不到一些规则，或者做成土豆丝那种云集，
做云集的最大的好处应该是排除了绝大多数会导致用户出问题的几率，能更专心的修bug。在别的fq交流群，经常见到用户因为规则导致的使用问题，当然多了维护成本。。。

*还有一个，有些人是路由翻，比如家庭网络路由翻，此时只需要走REJECT或者drop的规则，能否加个设置或者场景什么的嘛。

**Comment by alexazhou** [comment]
感谢你很详细的反馈🙏

## bug 反馈

### 1 输入的 skip proxy 只识别了一部分
advanced 里面配置项的文本输入框，有纠正格式的功能，输入的字符串需要用英文逗号隔开，格式不对的会被自动删掉

### 2 断开 wifi 网络未切换 
应该是偶尔会有这种情况，就是有比较小的概率会监控不到网络状态发生改变，如果你可以稳定复现这个，那么单独开个 Issue，我就可以修复了

## 细节

### 1，current session下的数据会清空

应该是由于网络状态改变了，所以后台重启服务时，重新开启了 session，而界面上面的 session 没有刷新，这时从 saved session 里面可以看到新的和旧的 session

### 2，request detail左滑至上一级有点掉帧

上一级是 request list 界面，这个界面采用了一种动态加载方式，主要特点是滑动的时间复杂度o(1)，就是不会随着记录增多而变慢，但是可能不是很快，目前没有更好的方式，先这样吧。

### 3，http request 最好能标记下哪个app使用的

后面版本尽量加上

### 4，rule里面的搜索不能查询关键字

搜索功能尚未完成，后面版本会修复

### 5，能不能根据ip的地址判定呢

可以设置 GeoIP 规则，IP-CIDR 规则来做到这一点

### 6，ui上的一些提示可不可以换一套风格

只是目前的重心在改进核心服务的稳定性，以及速度上，暂时没有修改 UI 的想法。当然等功能做稳定了可以考虑。

### 7，节点需要加排序和显示延迟，节点密码出应该加一个隐藏的眼睛

靠谱

### 8，应用节点和rule的提示其实可以放后台操作一下

这是故意弹出的框，如果没有这个提示，用户很可能会困惑并不能确定对规则的设置是否已经生效了


## 希望支持的功能：

### 1 能根据规则对流量进行分流。
这个已经可以了吧

### 2 希望支持SSR及最新加密方式，
后期可以考虑

### 3 url-rewrite功能，
这个在计划中，后期可能会提供一个比现有的 url-rewrite 更好的实现方式

### 4 自动选择最优节点并可以自定义参数
在计划中

### 5 希望可以对规则统计，或者做成土豆丝那种云集
计划加入规则的统计功能，以及在线规则集，就是需要些时间

### 6 场景模式
后期会加入

**Comment by unknowntokyo** [comment]
好的，谢谢dalao了～

**Comment by unknowntokyo** [comment]
dalao能给个tf吗……我记得上次申请了   好久没回信
