### ISSUE TITLE
屏蔽爱奇艺广告不成功

### ISSUE THREAD

**Issue by PJovy** [AnyFlowApp/AnyFlowApp-issues#34]
使用的是逗比极客的surge过滤规则，但是屏蔽爱奇艺广告不成功，surge成功。规则地址
https://github.com/PJovy/Surge/blob/master/Surge.conf

**Comment by alexazhou** [comment]
Work mode 是否已经设置成了 Rule Proxy？

规则只有在 Rule Proxy 模式下才会启用

如果 work mode 设置没有问题，那么麻烦提供具体复现方法，我会去验证

**Comment by PJovy** [comment]
已经设置。复现方法：
首先 add  proxygroup.使用url导入我开始发的规则地址，然后设置 rule proxy.打开vpn开关。
接着打开爱奇艺，无法屏蔽爱奇艺广告。
btw,这个规则在surge里面是可以屏蔽爱奇艺广告的

**Comment by alexazhou** [comment]
还有一点，规则组 Enable 了吗？

规则组前面打勾表示 Enable，只有 Enable 的规则组才会生效

**Comment by PJovy** [comment]
勾了的，放心。基本使用已经没有问题了，只是爱奇艺的规则这个不能用，其他的暂时正常。辛苦作者排查一下原因

**Comment by alexazhou** [comment]
ok，多谢反馈 :-P。

我今天之内会验证了答复你。

**Comment by alexazhou** [comment]
对了，我们说的是爱奇艺 app ，就是里面随便打开一个视频都有的片头广告，而不是爱奇艺网页对吧

**Comment by PJovy** [comment]
是的，是爱奇艺app

**Comment by alexazhou** [comment]
目前是这样，我测试了导入这份规则 4152 条，然后播放爱奇艺视频，发现确实命中了很多次 reject 规则，但广告可以播放。

还不清楚原因究竟是规则没有覆盖全，还是匹配时漏过了，我后面需要做更详细的对比测试，有结果了我最更新在这里

**Comment by PJovy** [comment]
确实是有遗漏的。不过不得不感叹，软件质量很高，速度非常快,一般使用,和surge体验相当。辛苦作者了，祝平安夜，圣诞快乐

**Comment by alexazhou** [comment]
哈哈，夸奖啦，也祝你平安夜快乐～

**Comment by Traxsw** [comment]
Surge 也屏蔽不了吧，不过我只倒入了 Reject的规则

**Comment by z82190716** [comment]
记得是要杀掉一个IP地址的，surge放弃了，现在不明
