### ISSUE TITLE
大家圣诞节快乐，设置问题懂得进来帮忙回答下

### ISSUE THREAD

**Issue by learnsss** [AnyFlowApp/AnyFlowApp-issues#35]
仍然连不上网络，感觉是我设置有问题吧。analytics tab下enable开启的情况下连接，发现http requests和dns要么是灰色的，要么是点开后什么请求也没有。还有就是applying rule这个一直转，根本停不下来，只有重启，所以我仍然连不上网络…

**Comment by CoderRunner** [comment]
我也会有这样的情况
一般我会断开vpn，清anyflow后台
重新打开AnyFlow连接

奇怪的是我经常需要连接后立即断开再连接才正常

**Comment by alexazhou** [comment]
圣诞快乐～
我正在写 Trouble-Shooting 文档 (/ω＼)

**Comment by CoderRunner** [comment]
不过连好之后还是很给力的
把IP-CIDR的bug解决了基本就可以长开了，毕竟要用tg🙈

**Comment by CoderRunner** [comment]
@alexazhou 不过会卡在Applying rules一直转圈圈真的需要定位下问题啊，我遇到类似的情况了
Applying rules
Applying DNS
Reloading Tunnel
Reloading service
只要发生卡的情况，基本上这些设置问题都会出现

**Comment by CoderRunner** [comment]
圣诞快乐🎄🎄

**Comment by alexazhou** [comment]
@CoderRunner 

抱歉哈，我这边没办法重现 Applying Rules 卡住的情况，可以对照这里面的写的，提供日志给我么？

https://github.com/AnyFlowApp/AnyFlowApp-issues/blob/master/Trouble-Shooting.md

**Comment by CoderRunner** [comment]
昨天给你发了封邮件啊，没有收到吗？

**Comment by alexazhou** [comment]
@CoderRunner 

抱歉，开始没看到

现在翻出来了，原来是混在一堆 Github 的邮件里面了😅，我去查查看

**Comment by alexazhou** [comment]
从 Log 中来看，好像是监听代理端口失败了？

因为一直没有 accept 到连接，我想办法再查查原因

**Comment by CoderRunner** [comment]
好的，这个只发生在我连家里WiFi的情况下
后续还有什么问题我可以帮忙测试

**Comment by learnsss** [comment]
@CoderRunner 我的问题可能更大一点，重装软件都不行，可能对ios9不太友好( ▼-▼ )，圣诞快乐！！！

**Comment by learnsss** [comment]
@alexazhou  排查后还是一如既往，宝宝心好累，已发邮件，还是祝百忙之中的老大圣诞快乐！！！( ¯(∞)¯ )

**Comment by CoderRunner** [comment]
@Mr-WK 我开4G是可以连接的，然后打开WiFi，这样就正常，你可以试试

**Comment by alexazhou** [comment]
@Mr-WK 

别着急，我也收到了你的日志。从日志看你们遇到的是类似的情况，我再研究研究，有望下个版本解决。

**Comment by learnsss** [comment]
@CoderRunner 我的还是不行，我可能是酋长( ╯□╰ )

**Comment by learnsss** [comment]
@alexazhou 恩，好像连不上的也不是我一个人，我加的几个群里也有几个买了连不上的,,ԾㅂԾ,,。是1.4修复吗？是的话下次更新大约在什么时候，好让我有个盼头o(^▽^)o

**Comment by alexazhou** [comment]
@Mr-WK

主要困难在于我这边没有测试环境，没办法重现问题，但我会改写一部分代码。1.4 很可能可以修复目前某些情况下不能连接的问题。
 
和更新 v1.2，v1.3 时一致，目前基本上是每周更新一次

这次苹果放假 12 月 23-27 （太平洋时间），大概 12 月 29 （中国时间）我可以提交代码，然后就等审核通过了

TF 审核快一些，也就一个工作日，正式版慢点。

**Comment by learnsss** [comment]
@alexazhou 好的好的，期待！！！

**Comment by CoderRunner** [comment]
话说1.4 TF是今天吗🙈

**Comment by alexazhou** [comment]
@CoderRunner 

这次延期了一天到今天晚上提交代码，主要是 Debug 花了很多时间，预计明天可以 TF  :-P

**Comment by CoderRunner** [comment]
@alexazhou 
明白了😄 
AnyFlow稳定可靠才是最重要的，作者加油 ！

**Comment by alexazhou** [comment]
@CoderRunner @Mr-WK 

v1.4 版本已经提交了，很快会有 TF。

这次 DNSForwarder 接管了全部的 DNS 请求，应该可以修正和某些 wifi 的兼容性问题（按照我本地测试的结果来说）， 还请帮忙验证是否修复。

**Comment by alexazhou** [comment]
@CoderRunner @Mr-WK 

v1.4 build 2 TF 中，还有出现之前的 wifi 兼容性问题吗？

**Comment by learnsss** [comment]
@alexazhou 感觉仍然有，从昨天更新1.4到现在，出现了如下问题：
1、总共出现3次微信无网络连接，网页过程中有4次网络连不上情况，视频软件中出现了1次（关掉软件或使用其它类似软件正常）
2、出现了N次闪退，使用过程中的好多次闪退，在邮箱、微信、看视频、听音乐、浏览网页中都出现了闪退
3、有一次一直在连接到VPN，就是连不上，重启后才解决该问题
——————————————————————————————————————————————
    总体而言，比上次好很多，至少可以连上网了虽然仍然出现上述（之前版本都连不上网( ▼-▼ )），而且发现导入规则中无reject规则（是把这部分规则删掉了吗），暂时就有这些问题，如发现其他问题再来反馈！！！

**Comment by alexazhou** [comment]
多谢反馈。
1，偶发性无网络连接可能出现的原因比较多，比如规则或者 Proxy，主要是我本地没有这些情况，所以这个先继续观察吧
2，闪退是指 AnyFlow App 闪退，还是指后台 VPN 模块退出了？
3，偶尔可能有这种问题，因为我本地复现不了，先继续观察吧

另外我这里并没有对 Reject 规则作特别处理，如果有发现导入某一份规则，里面 Reject 消失的情况，可以把规则发给我分析

**Comment by learnsss** [comment]
@alexazhou 
1、规则我用的是abclite的，应该规则问题不大吧
2、后台VPN模块退出
3、恩，在设置里VPN里 一直显示正在连接，关闭重启软件都不行，只有重启机器才正常。

**Comment by alexazhou** [comment]
ABCLite 不带 reject 的那份规则应该是没问题的，带  Reject 的规则可能会引发一些问题。

在设置里面 VPN 一直正在连接，那表示 AnyFlow Core Service 启动的过程中出问题了，这时候应该也可以在设置中关掉。

另外你的设备，系统，或者使用环境有什么特别的地方吗？可否大概描述一下，这样我好分析

我本地完全没出现这类情况，所以我很困惑

**Comment by learnsss** [comment]
在设置里关闭，确实能关闭，但是在此开启软件时还是一如既往的正在连接。
没什么特别的地方吧...我感觉有两点可能有关吧1、运行内存512 过于小（可能只有surge对其友好？） 2、ios9系统

**Comment by CoderRunner** [comment]
@alexazhou 我这里暂时没问题，晚上再测试下。不过我在log里看到了很多DNSForwarder的WARN信息，我发一份log到你邮箱吧。

**Comment by alexazhou** [comment]
@CoderRunner 

多谢反馈，Log 已经收到。

主要原因是 v1.4 里面 DNSForwarder 接管了系统所有的 DNS 请求，有些地方没处理好就产生了 warn，目前看来不影响功能，后续我会想办法解决这个^_^

**Comment by alexazhou** [comment]
今天上线的 v1.4 已经修复了在某些 wifi 下面无法访问网络的问题
