### ISSUE TITLE
关于SKIP PROXY

### ISSUE THREAD

**Issue by CoderRunner** [AnyFlowApp/AnyFlowApp-issues#36]
在SKIP PROXY中输入：
192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlynatics.com
会自动过滤，结果只剩下：
*.local, e.crashlynatics.com

被过滤掉的部分是anyflow默认已经添加了的吗？

**Comment by alexazhou** [comment]
呃，输入框会自动校验数据，并且排除掉格式不符的数据

设计是这样的，SKIP Proxy 还没有支持添加 IP-CIDR 格式的配置

类似这样 192.168.0.0/16,10.0.0.0/8 的 IP-CIDR 格式可以添加到 **bypass-tun** 中去，那里面的配置会被自动 Skip Proxy
