### ISSUE TITLE
能加一个错误页面吗？

### ISSUE THREAD

**Issue by Traxsw** [AnyFlowApp/AnyFlowApp-issues#38]
safari访问一个无法访问的地址，能提示是匹配到reject or  drop规则 还是DNS查找失败，或者又是socket建立失败。谢谢

**Comment by alexazhou** [comment]
确实可以考虑。

目前可以从 Request 列表里面查看断开的原因，不过那里有时 reject 会显示为 remote disconnect。。。

后面会修复这个

**Comment by Traxsw** [comment]
那大约在哪个版本会加入

**Comment by alexazhou** [comment]
按我的理解，这个目前的优先级不高，所以还没确定哪个版本加入

你需要这个是做什么用途呢？

**Comment by Traxsw** [comment]
就排错会更直接点

**Comment by alexazhou** [comment]
测试规则的话，可以用 RuleTest 界面
