### ISSUE TITLE
掉线还是有点频繁，还有其他的bug

### ISSUE THREAD

**Issue by p0pfan** [AnyFlowApp/AnyFlowApp-issues#40]
1. 我最近刚刚开始体验，之前一直用surge 1.2.5的！发现用anyflow的时候，掉线比较频繁。但是surge真的一直都是连着的。    

2. 当我用moke刷微博的时候，不知道怎么回事就退出了；用网易云音乐听歌的时候（就只听歌），当我过几分钟重新打开手机，发现又自动退出了。  
不知道是不是因为规则设置的原因。  
我用的是  
https://raw.githubusercontent.com/p0pfan/Surge/p0pfan-spilit/Reject.conf  
https://raw.githubusercontent.com/p0pfan/Surge/p0pfan-spilit/Proxy.conf  

3. 还有发现我一开始用的时候由于错误的选择了socks5的方式，并且没有添加任何规则，直接是direct的方式，当开启anyflow以后，我去访问Google之类的网站，anyflow也会自动掉线。 
4. 当我打开anyflow使用时，我没有开启 analytics，但是如果遇到某些东西无法加载的时候，我会使用这个功能，这个时候我再去打开（这个时候并未关闭anyflow），有时候会出现一直在加载的框，有时候我在它显示加载的框的时候，去关闭anyflow，也无法使加载的框关闭，只有把整个程序关掉，重新打开才可以。
5.  analytics有时候打开了，但是会出现current session无法点击的情况。

6. saved session里面的delete all 的功能好像没有用，得一条一条删除。有时候我会在没有关闭analytics的情况下想去删除saved session，但是只能一条一条删除。

**Comment by alexazhou** [comment]
你目前使用的 app 版本号是 1.4 吧，请问手机系统版本多少，是否越狱？

**Comment by alexazhou** [comment]
多谢你的反馈，情况如下：

1 & 2 & 3 ，总的来说就是自动断开的不同表现形式，可能的原因是，目前 1.4 版本确实有些不稳定，另外如果你越狱了的话，在越狱系统下也会不稳定。规则跟这个应该没太大的关系。新的版本很大程度上修正了不稳定的问题，正在等待审核。

4 & 5，1.4 版本的有个组件叫做 APP Message Bus 有时会不稳定，导致 APP 和 Tunnel 通讯失败。你说的这两个问题就是和这个有关。目前新版本也已经修复了。

6，那个 delete all 其实是删除了，就是没有自动刷新界面。返回重新进去就好。

**Comment by p0pfan** [comment]
谢谢回复，我目前的版本是1.4，iOS10.2，未越狱的

**Comment by learnsss** [comment]
@alexazhou 老大，我的一样，每次打开qq邮箱打开收件箱和垃圾邮件必闪退（其他没试），看视频过程中也莫名闪退。

**Comment by alexazhou** [comment]
@Mr-WK 

qq 邮箱是 app 么，还是网页呢？

可否具体跟我描述一下，我去试试看

**Comment by learnsss** [comment]
@alexazhou  就是app的qq邮箱，感觉闪退不是因为app的原因，再干其它也有闪退。

**Comment by alexazhou** [comment]
稳定性问题在 1.4.1 中基本已经修复
