### ISSUE TITLE
微信朋友圈图片加载的问题

### ISSUE THREAD

**Issue by CsHeng** [AnyFlowApp/AnyFlowApp-issues#41]
微信朋友圈加载图片请求『ipv6』地址，然后跑到proxy去了，导致加载时间超级。。。

现有的版本有没有什么办法可以处理一下，用的最新tf 1.4.1 build6

![image](https://cloud.githubusercontent.com/assets/1481956/21759006/cebda7d2-d67b-11e6-97c7-8fa5ebd6ddb9.png)
![image](https://cloud.githubusercontent.com/assets/1481956/21759009/d260c41e-d67b-11e6-8b15-632374a73f3f.png)

**Comment by alexazhou** [comment]
是不是设置了 default policy 为 proxy？然后通过 GeoIP CN  指定中国区 direct？

因为 geoip 对 ipv6 地址是无效的，所以会跑到国外去

**Comment by alexazhou** [comment]
已经确认过这里是上面描述的原因。

**Comment by CsHeng** [comment]
再次测试确认，即使default policy为direct，而且匹配到direct，这样一个链接的处理时间还是非常久，一直等到客户端断开(client disconnected)

![image](https://cloud.githubusercontent.com/assets/1481956/21849899/13f25280-d843-11e6-87f4-7ad231bcd598.png)
![image](https://cloud.githubusercontent.com/assets/1481956/21849900/179593c0-d843-11e6-8598-1a5c54018d95.png)

**Comment by CsHeng** [comment]
不对不对。。锅在ipv6，我关了。

但还是特别希望有一种方式能在default policy proxy的情况下direct朋友圈流量，因为可以少写好多规则
