### ISSUE TITLE
这不是一个bug~      1.4.1更新了什么。。？

### ISSUE THREAD

**Issue by wxiubin** [AnyFlowApp/AnyFlowApp-issues#42]
另外大牛牛能不能在readme.md加一个TODO。。？好让大家有个期待啊，毕竟很多人可能买了APP也不会加tf，想知道大牛的进度和下一个功能是什么？

**Comment by p0pfan** [comment]
比1.4稳定了很多，至少我下午连着到现在没有出现程序退出的情况。加个TODO挺好的。

**Comment by alexazhou** [comment]
主要是改进了稳定性和速度，具体可以参考 appstore 的版本说明

ToDo 暴露了太多信息，不是很方便加上😢
