### ISSUE TITLE
启用anyflow路由器管理界面登入不了。

### ISSUE THREAD

**Issue by z82190716** [AnyFlowApp/AnyFlowApp-issues#43]
启用anyflow路由器管理界面登入不了。而且anyflow出现自动停止的情况，ios 10.2 国行6s。angflow1.4。1.3也是进不去，但是未发现自动停止服务。

**Comment by alexazhou** [comment]
1，关于路由不能访问：是否是使用了 proxy 规则，或者 default 设置为 proxy 导致访问路由时走了代理？
可以切换 work mode 为 direct 进行测试，看是否可以访问，如果可以，那就是规则的问题。

2，请升级到 v1.4.1，这一版本修正了之前导致自动退出的问题，应该已经很难自动退出了

发自我的 iPhone
