### ISSUE TITLE
闪退bug

### ISSUE THREAD

**Issue by harriks** [AnyFlowApp/AnyFlowApp-issues#48]
版本 : 1.5build 3 
问题 : 在开着surge的情况下,再打开anyflow 然后出现会闪退的bug (但闪退后又会马上启动),触发次数蛮多的.   翻了下日志提示端口冲突.
`
2017-01-17_143025 <FATAL> [DNSForwarder] local listen socket bind failed with error:Error Domain=NSPOSIXErrorDomain Code=48 "Address already in use" UserInfo={NSLocalizedDescription=Address already in use, NSLocalizedFailureReason=Error in bind() function}
got a signal 6
`

具体见附件. 

[log.zip](https://github.com/AnyFlowApp/AnyFlowApp-issues/files/710177/log.zip)

**Comment by harriks** [comment]
补充说明下:
闪退了后 又会马上启动

**Comment by harriks** [comment]
后来发现无法直连（按故障排除里的步骤做了），重启程序后问题依旧。最后试着删掉重下 才可以（之前没下过老版本）。

**Comment by harriks** [comment]
继续补充问题：
开启分析功能后 明显感觉换页有卡顿 不流畅。
同样功能surge则不会有这种问题 希望开发者继续完善啊

**Comment by alexazhou** [comment]
请问设备型号，以及系统是什么？还有是否越狱？

**Comment by harriks** [comment]
iphone6    9.3.5 没越狱。

**Comment by alexazhou** [comment]
1，开启 surge 后，再开启 anyflow，我这边是正常的，没能重现你提出的问题。另外我发现之前的 log 输出的有些问题，我已经在代码中修正了，现在会有更多的信息，可以等下个版本观察看看。

2，关于卡顿，surge 有个选项是 dump request body，这个选项开启之后，才是跟 anyflow 处在同一情况下，这样才好进行对比。Anyway 后续会优化性能。

**Comment by harriks** [comment]
1、卡顿 问题，下午在surge里开启dump body and save 比较了下 个人感觉还是anyflow略卡，可能还需要继续完善；
2、闪退问题是偶尔性的。等下版本日志详细了在一起测吧
