### ISSUE TITLE
无法加载虾米的歌曲

### ISSUE THREAD

**Issue by p0pfan** [AnyFlowApp/AnyFlowApp-issues#51]
[LOG.zip](https://github.com/AnyFlowApp/AnyFlowApp-issues/files/721818/LOG.zip)
打开anyflow不管是direct还是rule proxy 下都无加载歌曲，歌曲进度条只显示00:00；但是使用网易云则是正常的

PS: Log下自动删除日志的功能好像不起作用啊！默认是开启的，但是我看了一下我12月份的日志都还在啊

**Comment by learnsss** [comment]
我一般都手动删除（一天一删），不然乞丐版空间受不了,,ԾㅂԾ,,

**Comment by alexazhou** [comment]
1，虾米无法播放的问题已经修复，正在审核中
2，Log 自动删除确实有问题，下个版本修正

**Comment by alexazhou** [comment]
截至 1.5.1 版本，虾米音乐问题已经修复，可以更新看看

（Log 还没有）
