### ISSUE TITLE
删掉log的日志后一直闪退

### ISSUE THREAD

**Issue by iuhux** [AnyFlowApp/AnyFlowApp-issues#54]
enable analytics的时候，手工删掉log里面的anyflow和tunnel的日志文件后app就一直闪退，删掉重装才行。

**Comment by alexazhou** [comment]
可以告诉我具体复现步骤么？我想办法重现一下

**Comment by luckyWK** [comment]
更新版本后一直闪退，不知道什么原因，一会重装试试

**Comment by luckyWK** [comment]
重装后正常了

**Comment by alexazhou** [comment]
找到问题了，已经提交了修复版本

是自动删除 log 的代码有问题，当一个 log 都没有的时候，就会出现闪退的情况...

目前如果遇到这个bug，只能重新安装来解决

**Comment by iuhux** [comment]
好的。谢谢亲。解决很及时
