### ISSUE TITLE
WI-FI的时候使用rule-proxy可以翻墙但打不开国内网站，4G网络没有问题

### ISSUE THREAD

**Issue by iuhux** [AnyFlowApp/AnyFlowApp-issues#55]
使用4G流量用默认的rule-proxy既可以翻墙也可以打开百度，换成Wi-Fi还能翻墙单身打不开百度，dns问题。

**Comment by alexazhou** [comment]
我这边 4G 环境下使用没问题，可以告诉我具体的复现方法么？

或者提供给我日志也可以

**Comment by iuhux** [comment]
现在复现不了了。下次再出现问题我会贴上日志
