### ISSUE TITLE
[Crash]引起程序闪退的一种情况

### ISSUE THREAD

**Issue by z-jack** [AnyFlowApp/AnyFlowApp-issues#56]
复现方式如下：
1. 进入"Config"
2. "Add Rule Group" - "Empty group"
3. 在不输入名称的情况下点击"Proxy Rules"即会闪退

**Comment by alexazhou** [comment]
已经复现，我会尽快修复这个

**Comment by alexazhou** [comment]
已经修复了，就等下次版本更新了

**Comment by alexazhou** [comment]
1.6.2 已经修复
