### ISSUE TITLE
有一个未知来源的 ipsec interface，同时网络延迟很大

### ISSUE THREAD

**Issue by pengtikui** [AnyFlowApp/AnyFlowApp-issues#60]
使用后，网络延迟变得极高，达到几秒甚至十几秒（使用腾讯手机管家的网络测速，关闭后网络延迟为十几毫秒），网页打开要五秒以上甚至无响应，无论是国内还是国外的网站，使用 Wingy、Shadowing 等则正常。

机型：iPhone 7
系统：iOS 10.2.1
AnyFlow 版本：1.6 build 2

### 使用方法

* 从 App Store 下载安装
* Config -> Add Proxy 添加服务器信息，Type 为 Shadowsocks
* Work Mode 选择 Rule Proxy
* Rule Group 选择 Default v0.2
* 其他保持默认

将 Log Level 设为 ALL，然后用 Safari 打开 Google、V2EX 和爱范儿三个网站，日志如下：

[logs.zip](https://github.com/AnyFlowApp/AnyFlowApp-issues/files/752807/logs.zip)

**Comment by alexazhou** [comment]
多谢反馈，我来分析一下日志。

另外可以测试一下，将 Work Mode 设置为 Direct 的情况下，还有延迟么？

**Comment by alexazhou** [comment]
我看到 log 里设备有张 ipsec 的网卡

请问你有在同时使用其他 VPN 之类的软件吗？

**Comment by pengtikui** [comment]
将 Work Mode 设置为 Direct 依旧有延迟

装了一个 Shadowing，昨天将其删除，在 AnyFlow 中 Reset VPN 也是如此

**Comment by alexazhou** [comment]
Direct 模式有延迟，那么就不是 Proxy 的线路原因。

从日志中来看，没有异常的信息，就是连接很慢，例如访问 V2EX 从开始连接到连接成功，就花了 4 秒😓，可以想象这样会很慢

我确定正常情况下是不会有 ipsec 的网卡，所以很可能跟这个有关系，建议

1，首先确认 Shadowing 已经卸载干净了，包括 app，以及 VPN 设置中没有 shadowing 的相关信息
2，重启手机

**Comment by pengtikui** [comment]
好，我先试一下

**Comment by pengtikui** [comment]
问题依旧，中间 AnyFlow 还出现一直闪退的情况重装了一次，下面是新的日志

[logs.zip](https://github.com/AnlowApp/AnyFlowApp-issues/files/752821/logs.zip)

**Comment by alexazhou** [comment]
呃，这个日志没办法下载，你确认下传好了吗

**Comment by pengtikui** [comment]
[logs.zip](https://github.com/AnyFlowApp/AnyFlowApp-issues/files/752822/logs.zip)

**Comment by alexazhou** [comment]
日志已经分析，ipsec interface 依然存在，我怀疑是所有从 VPN 模块出来的流量，都通过 ipsec 处理了，所以会慢。

你知道这个 ipsec 怎么来的么？有没有安装过其他这类的 app，或者是描述文件？

系统设置 > VPN 中有 ipsec 相关的东西吗？或者同类 App 呢？

我猜你找到这个 ipsec 是哪个 app 带来的，然后删除掉它就可以解决问题了

**Comment by pengtikui** [comment]
系统设置 -> VPN 里现在只有 AnyFlow，同类软件也都删除了，也没有任何描述文件 :cry:

**Comment by alexazhou** [comment]
抱歉哈，我也不知道这是为啥😓，目前只能确定那个 ipsec 接口很奇特。再从 direct 模式连接慢的情况来看，很像是流量走了 ipsec 接口导致的。

还是得靠你自己去找到原因搞定这个 ipsec 。

看到 ipsec 接口的方法是把 log level 设置为 debug，然后在 tunnel 的 log 很靠前的地方可以看到网络接口信息，里面有 ipsec。

如果你还有其他 iOS 设备的话，可以作一下比较，正常情况下是没有 ipsec 这个接口的。

**Comment by alexazhou** [comment]
另外一个办法是试试 

通用>还原网络设置

看是否可以清除掉这个接口

**Comment by pengtikui** [comment]
还原网络设置，情况依旧如此，而且还有 ipsec，在 iPad 上试了一下，情况也是如此，但是没用 ipsec 😢

**Comment by alexazhou** [comment]
把 ipad 的 log 贴一下我帮你分析吧。 

另外你的网络环境是怎样的呢？建议切换 wifi ／4G 来试试看，判断一下是否特定网络下会出现这个问题

**Comment by pengtikui** [comment]
手机使用 WiFi 和 4G 情况都是如此，iPad 也还原了网络设置，日志如下：

[ipad_logs.zip](https://github.com/AnyFlowApp/AnyFlowApp-issues/files/752834/ipad_logs.zip)

**Comment by alexazhou** [comment]
现在比较可能的有两种可能：

1，ipsec 原因，那么应该是 iphone 在 wifi／4g 都不正常，ipad 正常
2，wifi 网络原因，那么应该是 iphone 4g 正常，wifi 不正常，ipad 不正常

我分析了 ipad 的日志， ipad 访问 v2ex 是正常的吧，建立连接时间大概 1s，那么基本可以认为是第一种情况了

**Comment by pengtikui** [comment]
iPad 上使用腾讯手机管家网络测速，延迟也是异常的高，有些网站打开也是很慢。

唉，折腾一天了，我还是先换个软件用着吧，真是麻烦你了。

**Comment by alexazhou** [comment]
抱歉哈，没给你带来好的体验 😅

如果后续有其他有帮助的信息，可以回复在这里，我会继续排查

**Comment by pengtikui** [comment]
嗯，好的
