### ISSUE TITLE
ss特殊符号的密码连接不上

### ISSUE THREAD

**Issue by ghost** [AnyFlowApp/AnyFlowApp-issues#62]
iphone6
ios10.2.1
软件版本1.6

亲测ss密码中间有~符号连接不上，修改ss密码去掉这个符号可以连接上。其它符号没有测试。
不知道其他人有没有遇到同样的问题。

**Comment by alexazhou** [comment]
目前没有其他人反馈这个情况，我本人的密码中也是有字符的可以正常使用。 

是不是中文符号和英文符号的原因？

**Comment by zywsss** [comment]
修改密码去掉~符号anyflow也能正常连上，有这个符号anyflow就不行。同样有这个符号的密码在wingy、potatso上都能连上。

**Comment by zywsss** [comment]
而且尝试卸载重装过

**Comment by zywsss** [comment]
加密方式aes_256_cfb

**Comment by ghost** [comment]
还真没注意中英文符号。。。谢作者提醒，又试了一次果真是中英文的问题。问题已解决。
