### ISSUE TITLE
iOS9 环境下有概率出现微信一直连接中 

### ISSUE THREAD

**Issue by alexazhou** [AnyFlowApp/AnyFlowApp-issues#64]
同时朋友圈可以访问，网页可以打开，怀疑是 DNS 请求未被 DNSForwarder 捕获到导致的

目前有两位用户反馈，共同点是 iOS9.3.5

**Comment by alexazhou** [comment]
如果还有人遇到这样的问题，有更多信息可以提供的，可以继续提交在这里，我会尝试复现修复

**Comment by alexazhou** [comment]
已经成功复现了这个问题，如果没有意外下个版本就能修复

**Comment by tianmw** [comment]
QQ，whatsapp，旺信等IM app都出现类似问题。

**Comment by alexazhou** [comment]
已经修正，下个版本就包含这个修复了

**Comment by alexazhou** [comment]
1.6.2 已经修复
