### ISSUE TITLE
mtalk.google.com不走代理

### ISSUE THREAD

**Issue by flaming** [AnyFlowApp/AnyFlowApp-issues#73]
ios最新版，默认规则。联通4g网络，shadowsocks代理
google作为关键字应该是走代理的，rule test的结果也是proxy。

但是实际在chrome中用语音搜索的时候，查看日志可以看到www.google.com:443这些都走proxy了，但是mtalk.google.com:443却是卡住了，点开详细信息，POLICY却显示wait to judge。

**Comment by alexazhou** [comment]
为了提高性能 AF 在请求结束（HTTPS Tunnel 模式下为连接断开）时，对规则的判定结果进行写入。

wait to judge 表示连接还未断开，所以结果还没有写入

可以通过 Rule Test 页面来试试看，可以直接得到域名对应的判定结果

**Comment by flaming** [comment]
我在问题描述中已经说过了，rule test的结果的确是Proxy，但是实际访问过程中，chrome显示无法连接服务器。换成surge或者wingy都没有问题。
![img_1480](https://cloud.githubusercontent.com/assets/1780629/24233997/c903d3a0-0fd0-11e7-94ac-f9c6854c2ea0.PNG)
![img_1481](https://cloud.githubusercontent.com/assets/1780629/24233999/c9ec9842-0fd0-11e7-9337-f0e4319a4503.PNG)
![img_1482](https://cloud.githubusercontent.com/assets/1780629/24234000/cae127e0-0fd0-11e7-805c-fe2568d0ea72.PNG)

**Comment by alexazhou** [comment]
抱歉，开始没注意到你已经进行了 Rule Test。
AnyFlow 是由后台的网络服务和前台的 App 界面组成的，这两部分独立运行。

如果 Rule Test 的结果是 Proxy，那么实际就是 Proxy，只是由于连接还没有断开，所以后台服务没有把结果保存到文件系统，导致前台 app 读取状态为 wait。为了确认这个，你可以请求后关闭 chrome app，这样连接会断开，然后结果会被写入文件，就可以查到真正的代理情况了。
