### ISSUE TITLE
采用默认规则 王者荣耀无法进入对战,可以进入界面,没有办法进行对战游戏....

### ISSUE THREAD

**Issue by aircjm** [AnyFlowApp/AnyFlowApp-issues#74]
系统版本:
IPhone5s IOS 10.2.1

软件版本:
version 1.7 bulid 2

软件设置:
work mode  是RuleProxy

Rule Group 是Default 2.0
Default Proxy 是 Direct

每次打游戏都要退出AnyFlow 非常不方便
不是规则的问题,没有设置任何和QQ相关的规则

在App Store 里面有人评论和我出现一样的问题

问题非偶现. 麻烦看下哪里有问题,会造成非规则的正常网络请求被中断,麻烦定位下,谢谢

之前已经邮件发过日志给你,并没有回复该问题

**Comment by alexazhou** [comment]
多谢反馈，已经确认存在这个问题

后续版本修复（抱歉最近一直在忙，预计4月内会修正，当然我会尽快）

**Comment by aircjm** [comment]
这个非规则内的正常网络请求被阻塞 是偶然情况吗?? 心里有点虚

**Comment by alexazhou** [comment]
目前看来并非偶然，是 app 设计导致的必现 bug。

**Comment by alexazhou** [comment]
在 V1.9.1 中，王者荣耀问题已经修正了
