### ISSUE TITLE
Cannot connect to network on the first time starting software

### ISSUE THREAD

**Issue by theodoruszq** [AnyFlowApp/AnyFlowApp-issues#76]
I am using iPhone 6s and iOS 10.3. 

I can not connect to some website, such as <baidu.com> or <google.com> after everything has been settled. The issue has been solved after iOS prompting a dialog requesting the `Data use` permission. 

So  maybe it is better to request the permission primarily to avoid this.

Thanks for your contribution.

**Comment by alexazhou** [comment]
Thank you，I want to make some confirm，Does the problem happened at first time launch anyflow app after install？

 Or every time start anyflow app？

**Comment by theodoruszq** [comment]
The first time I launch anyflow app.

**Comment by alexazhou** [comment]
I think that's a iOS bug, because many other app also happend probability

So i can do nothing but give a explain in app document

**Comment by theodoruszq** [comment]
Get it, thanks.
