### ISSUE TITLE
有无支持SSR的计划？

### ISSUE THREAD

**Issue by liuminglm** [AnyFlowApp/AnyFlowApp-issues#77]
本来想入的，但是发现不支持SSR，想知道有无打算支持，以及大概的时间表，谢谢

**Comment by alexazhou** [comment]
目前还不保证能支持 SSR =_=，但会尽量给大家提供更好的软件

**Comment by liuminglm** [comment]
谢谢回复，那我还是先买个支持SSR的用了，不好意思了
