### ISSUE TITLE
增加通过URL或文件导入Rule Group

### ISSUE THREAD

**Issue by CoderRunner** [AnyFlowApp/AnyFlowApp-issues#8]
目前好像只能手动一条一条地加

**Comment by alexazhou** [comment]
很同意

**Comment by CoderRunner** [comment]
试用了1.2版本，chacha20等加密方式有了，不过还是不能批量导入规则
手动导入有点太麻烦了

另外，希望作者能开TF测试，App Store的上架时间平均都要两三天，不太适合初期快速迭代测试

**Comment by alexazhou** [comment]
@CoderRunner 

感谢你的建议。

1，导入规则正在开发中，下个版本（v1.3）就有了 :-)
2，我也在考虑 TF 的事情，让一些感兴趣，且知识储备足够的用户（主要是对网络这块有一定了解），参与测试应该是利大于弊的。所以我会理一下相关的东西，今天或者明天就可以让大家申请了。

**Comment by alexazhou** [comment]
至 v1.3 版本，已经可以导入 Surge 规则
