### ISSUE TITLE
Network Doctor 的 PROXY ACCESS 不支持重名

### ISSUE THREAD

**Issue by metowolf** [AnyFlowApp/AnyFlowApp-issues#80]
在 PROXY 中添加多个 Name 相同的代理，在 Network Doctor 中只会显示一个

**Comment by alexazhou** [comment]
😓，确实没想到，会出现多个代理 name 相同的情况

这地方不好修，因为多个代理名字一样的话，也是没办法区分的

我去限制一下不能添加同样名字的代理吧
