### ISSUE TITLE
建议开放配置文件编辑、启用TG群、启用TF测试

### ISSUE THREAD

**Issue by CsHeng** [AnyFlowApp/AnyFlowApp-issues#9]
现在纯UI的方式，全手工点击修改，在手机上输入修改，效率太低。

另外也建议开启TG群，开放TF测试，AppStore上线流程不利于这个阶段快速测试对软件的完善。

**Comment by alexazhou** [comment]
1，配置文件编辑这个需求，其实想表达的是

“现在配置太不方便了，不如让我们自己来编辑文本吧”

而不是全 UI 的方式有问题，后续我会把这个改的方便了，其实这个问题就解决了

另外一个原因是，编辑配置文件的方式，不利于 AnyFlow 的配置模型的扩展，所以我认为还是不开放配置文件编辑会比较好。

2，目前先不建立 TG 群，统一在 GitHub 比较好，所有记录都可以追溯，后面的人也可以看到

3， TF 测试正在考虑中，如果开放会在这里发布通知

**Comment by CsHeng** [comment]
1、是的，确实是因为配置太不舒服了，比如刚买完要使用的时候，发现要输入TG的8段CIDR，要输入地区，要输入SS配置信息，手机上输入不方便，简直要命。

而如果只是几个很简单的规则的话，很难模拟出用户真实使用环境，也就容易忽略一些大规模使用之后会暴露出来的问题。

3、期待。

另外我目前发现的问题，GEOIP CN，default proxy的逻辑，微信文章的打开速度比shadowrocket慢好多= =#

也提个feature，在HTTP Requests列表项，添加match到的policy？这样可以很简单调试规则，知道这条request究竟是direct了还是proxy了。

**Comment by alexazhou** [comment]
2，是因为现在 GeoIP 的库有问题，这版被我临时屏蔽掉了，所以估计全走了 Proxy
3，快速添加规则这个 feature 靠谱。现在从请求点进去，可以从 Policy 字段看到是否走的代理

**Comment by CsHeng** [comment]
刚看了一下，果然weixin域名的都跑proxy去了

**Comment by alexazhou** [comment]
至 v1.3 版本 GeoIP 和导入规则都已经 ok
