### ISSUE TITLE
安装完随即点击连接，提示没有配置，随即添加配置也不能立刻使用

### ISSUE THREAD

**Issue by itbdw** [AnyFlowApp/AnyFlowApp-issues#91]
功能强大，免费版本已经很可以了。收费版多了些方便的功能。

但是，不知道为什么，我刚添加完配置时，打开vpn，啥都打不开了。我打开网络医生，提示连接超时，重启了几次app，才好了。怀疑是否是因为我一开始就点击了连接，但是当时没有配置，所以缓存了一个错误的配置？

**Comment by w22gb8** [comment]
我也是这样，先用的免费版可以用，再用收费版就网络不通了。
https://github.com/AnyFlowApp/AnyFlowApp-issues/issues/90

**Comment by alexazhou** [comment]
每次启动 vpn 是个新的 tunnel， 并不会有缓存的逻辑在里面，应该不是这个原因

请问有办法可以复现吗？

**Comment by itbdw** [comment]
我的一台手机可以用了，我另一台手机一直不能连，我看了下，设置里面 anyflow lite 界面是空白的，而是蜂窝网络里也看不到 anyflow，是不是有时没弹出允许网络请求的设置？

![img_0125](https://user-images.githubusercontent.com/1267057/27184916-359b51e6-5216-11e7-94d6-1d6413c9ebaf.PNG)

**Comment by alexazhou** [comment]
如果没有弹出允许访问网络的弹窗，确实会有问题，就是网络完全访问不了。

不过网络弹窗这个是 iOS 系统的偶发 bug，App 没有已知的办法来规避😓。现在网上总结出来一些方法可以解决，例如重启等，你可以试试看

**Comment by itbdw** [comment]
嗯。。。我重启了，删除软件重装，都无效，不过就这样吧。。。我有一个手机能用

**Comment by itbdw** [comment]
我解决了……

我点击anyflow的帮助，发出了网络请求，他就提示我是否允许访问网络课堂……

发自我的 iPhone
