### ISSUE TITLE
ios上是否被下架？

### ISSUE THREAD

**Issue by moondigi** [AnyFlowApp/AnyFlowApp-issues#94]
显示此项目不再提供

**Comment by alexazhou** [comment]
因不可抗力原因，国区已被下架😓，其他区依然可用。

正式版用户可以从已购里面下载，也可以将 ID 转至其他区如加拿大。

**Comment by moondigi** [comment]
我这里还留着一个很老的版本，点更新的话更新不了
有一个日服的账号，有没方法转移到另外一个账号上的？

**Comment by alexazhou** [comment]
可以先删除，再从已购里面下载，这样应该可以

好像并没有办法在不同的 appid 中转移已购项目吧
